### ISSUE TITLE
ChromeOptions are not handled properly

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#166]
**Version**
2.1.0 and @next

**Short overview**
When configuring Chrome options via properties file, options have no effect or cause an error.

**Detailed error description**
Running a test in Chrome with ChromeDriver options configured in `testsuite.properties` has no effect or even causes the test to throw an error on startup.
For example, configuring `--disable-infobars --incognito` has no effect and Chrome starts in default mode with enabled infobars.
Configuring the browser window size even causes a crash on startup, so the test does not even run.

```
TypeError: Arguments must be {width, height} with numbers > 0
    at checkArg (/Users/shofmann/Documents/git/TA/sakuli/sakuli/sakuli/packages/sakuli-legacy/node_modules/selenium-webdriver/chrome.js:397:15)
    at Options.windowSize (/Users/shofmann/Documents/git/TA/sakuli/sakuli/sakuli/packages/sakuli-legacy/node_modules/selenium-webdriver/chrome.js:400:5)
    at /Users/shofmann/Documents/git/TA/sakuli/sakuli/sakuli/packages/sakuli-legacy/dist/context/selenium-config/chrome-options-factory.function.js:36:18
    at Object.ifPresent (/Users/shofmann/Documents/git/TA/sakuli/sakuli/sakuli/packages/sakuli-commons/dist/maybe.js:23:13)
    at /Users/shofmann/Documents/git/TA/sakuli/sakuli/sakuli/packages/sakuli-legacy/dist/context/selenium-config/chrome-options-factory.function.js:34:19
    at Object.ifPresent (/Users/shofmann/Documents/git/TA/sakuli/sakuli/sakuli/packages/sakuli-commons/dist/maybe.js:23:13)
    at Object.exports.chromeOptionsFactory (/Users/shofmann/Documents/git/TA/sakuli/sakuli/sakuli/packages/sakuli-legacy/dist/context/selenium-config/chrome-options-factory.function.js:33:15)
    at Object.exports.applyBrowserOptions (/Users/shofmann/Documents/git/TA/sakuli/sakuli/sakuli/packages/sakuli-legacy/dist/context/selenium-config/apply-browser-options.function.js:15:58)
    at Object.exports.createDriverFromProject (/Users/shofmann/Documents/git/TA/sakuli/sakuli/sakuli/packages/sakuli-legacy/dist/context/selenium-config/create-driver-from-project.function.js:48:38)
    at LegacyLifecycleHooks.<anonymous> (/Users/shofmann/Documents/git/TA/sakuli/sakuli/sakuli/packages/sakuli-legacy/dist/context/legacy-Lifecycle-hooks.class.js:72:69)
npm ERR! Test failed.  See above for more details.
```

**Steps to reproduce error**
Create a new test and add the `testsuite.properties` content attached below.

**Additional content**
testsuite.properties:
```
testsuite.id=integrationtest
testsuite.browser=chrome
selenium.chrome.arguments=--disable-infobars --incognito
selenium.chrome.windowSize.width=640
selenium.chrome.windowSize.height=480
```

**Comment by rahulmr** [comment]
@s1hofmann any TD for fixing this? Our application need this ASAP :)

**Comment by s1hofmann** [comment]
@rahulmr We're currently finishing some ongoing tasks. We've not yet fully discussed our upcoming release schedule. We might take this issue in consideration, but I can't promise a fixed release date, since we're quite busy at the moment.

**Comment by rahulmr** [comment]
@s1hofmann can you point out or guess where a fix is needed? I might help with some code. Send you a PR if I am able to fix the issue.

**Comment by s1hofmann** [comment]
Hi @rahulmr, we're not yet fully done with our current tasks, but I noticed that Chrome options are working fine in our integration test setup. If you want to investigate on this issue by yourself, the code dealing with browser options in general is located in

```
<sakuli_root>/packages/sakuli-legacy/src/context/selenium-config
```

**Comment by s1hofmann** [comment]
Hi @rahulmr,

could you give our latest snapshot release a try?
We updated the `selenium-webdriver` dependency which resolved the existing errors with ChromeOptions.

Simply run

```
npm i @sakuli/cli@next
```

to install our latest snapshot

**Comment by WWIJP** [comment]
We need as well these parameters: --allow-running-insecure-content --ignore-certificate-errors

**Comment by rahulmr** [comment]
Thanks @s1hofmann , will check and comment here.

**Comment by rahulmr** [comment]
@s1hofmann It is working fine. Just to confirm. Checked it today.
