### ISSUE TITLE
getDriver from undefined exception

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#314]
In the current 2.2.0 release some tests fail with an `getDriver from undefined` exception. Currently it is hard to reliably reproduce the error.

Acceptance criteria:

 - [x] Make the error reproducible in Sakuli or in Selenium
 - [x]  Identify the root cause of the error
 - [x]  Fix the issue if it is in Sakuli / Create a resilience strategy if the error is located in a Sakuli dependency
 - [x] Prevent error messages being sent to monitoring systems in case of an getDriver exception

**Comment by tnobody** [comment]
is there any error log with more information about when this error occurs?

**Comment by cliffle** [comment]
@tnobody here is a stacktrace of the _sakuli.log_
```
[Wed Jan 15 2020 14:16:26 GMT+0000 (Coordinated Universal Time)] ERROR: Error in testcase: A non StaleElementReferenceError is thrown during retrying;  
TypeError: Cannot read property 'getDriver' of undefined
Error: A non StaleElementReferenceError is thrown during retrying;  
TypeError: Cannot read property 'getDriver' of undefined
    at /testsuite/node_modules/@sakuli/legacy/dist/context/sahi/action/utils/create-with-retries.function.js:88:39
    at step (/testsuite/node_modules/@sakuli/legacy/dist/context/sahi/action/utils/create-with-retries.function.js:32:23)
    at Object.throw (/testsuite/node_modules/@sakuli/legacy/dist/context/sahi/action/utils/create-with-retries.function.js:13:53)
    at rejected (/testsuite/node_modules/@sakuli/legacy/dist/context/sahi/action/utils/create-with-retries.function.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)[Wed Jan 15 2020 14:16:26 GMT+0000 (Coordinated Universal Time)] INFO: Saved error screenshot at 'sakuli_test_suite/_logs/_screenshots/sakuli_test_suite/2020-01-15T14-16-26_error_sakuli_test_suite.png'
```
