### ISSUE TITLE
Sakuli dies silently on syntax errors outside `try {} catch {}`

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#324]
**Version**
2.2.0

**Short overview**
Sakuli dies silently and without any error when using `tc.addImagePath()`. I know that  `tc.addImagePaths()` is the correct function, but Sakuli should throw an error in case an unknown function is used.

**Detailed error description**
Here is a complete log output
```
  ____            _              _   _ 
 / ___|    __ _  | | __  _   _  | | (_)
 \___ \   / _` | | |/ / | | | | | | | |
  ___) | | (_| | |   <  | |_| | | | | |
 |____/   \__,_| |_|\_\  \__,_| |_| |_|
                                       
========================================

Initialized Sakuli with 1 Testcases

Writing logs to: sakuli_test_suite/_logs/sakuli.log
Started execution
→ Started Testsuite sakuli_test_suite
  → Started Testcase Foo
   → Started Step UNNAMED
```

**Steps to reproduce error**
```javascript
(async () => {
  const tc = new TestCase("Foo");
  tc.addImagePath("./assets");
  try {
     await _navigateTo("https://google.de");
  } catch (e) {
    tc.handleException(e);
  } finally {
    tc.saveResult();
  }
})();
```

**Comment by s1hofmann** [comment]
More generally, this error occurs whenever there's a syntax error outside the typical `try {} catch {}` block used in Sakuli tests.

For example:

```javascript
(async () => {
    const tc = new Testcase();
    try {
        tc.addImagePath("foo");
    } catch (e) {
        await tc.handleException(e);
    } finally {
        await tc.saveResult();
    }
})();
```

calling `addImagePath` inside the `try {} catch {}` block correctly reports the syntax error:

```
  ____            _              _   _
 / ___|    __ _  | | __  _   _  | | (_)
 \___ \   / _` | | |/ / | | | | | | | |
  ___) | | (_| | |   <  | |_| | | | | |
 |____/   \__,_| |_|\_\  \__,_| |_| |_|

========================================

Initialized Sakuli with 1 Testcases

Writing logs to: foo/_logs/sakuli.log
Started execution
→ Started Testsuite .
  → Started Testcase Testcase
   ⚠ Finished Step UNNAMED with state Error................................................................0.128s
  ⚠ Finished Testcase Testcase with state Error............................................................0.129s
⚠ Finished Testsuite . with state Error....................................................................0.162s
End execution

Failed to perform step :

TypeError: tc.addImagePath is not a function
at /private/tmp/t/foo/case1/check.js:6:12
    at /private/tmp/t/foo/case1/check.js:12:3
    at Script.runInContext (vm.js:131:20)
    at Script.runInNewContext (vm.js:137:17)
    at /private/tmp/t/node_modules/@sakuli/core/dist/runner/js-script-executor.class.js:21:35
    at new Promise (<anonymous>)
    at JsScriptExecutor.execute (/private/tmp/t/node_modules/@sakuli/core/dist/runner/js-script-executor.class.js:15:16)
    at SakuliRunner.execute (/private/tmp/t/node_modules/@sakuli/core/dist/runner/sakuli-runner.class.js:35:63)
    at async SakuliClass.run (/private/tmp/t/node_modules/@sakuli/core/dist/sakuli.class.js:58:9)
    at async Object.handler (/private/tmp/t/node_modules/@sakuli/cli/dist/commands/run-command.function.js:39:17)
```

whereas e.g. a misspelled `Testcase` also causes Sakuli to die silently:

```
```javascript
(async () => {
    const tc = new Testcase();
    try {
        tc.addImagePath("foo");
    } catch (e) {
        await tc.handleException(e);
    } finally {
        await tc.saveResult();
    }
})();
```

```
  ____            _              _   _
 / ___|    __ _  | | __  _   _  | | (_)
 \___ \   / _` | | |/ / | | | | | | | |
  ___) | | (_| | |   <  | |_| | | | | |
 |____/   \__,_| |_|\_\  \__,_| |_| |_|

========================================

Initialized Sakuli with 1 Testcases

Writing logs to: foo/_logs/sakuli.log
Started execution
→ Started Testsuite .
  → Started Testcase Testcase
   → Started Step UNNAMED
```

**Comment by svettwer** [comment]
Some refinement is required to create possible paths to find a solution

**Comment by cliffle** [comment]
A syntax error outside the try/catch would be rejected here :
https://github.com/sakuli/sakuli/blob/7e7b2aaebbd1ceb947a3b1ca54b59a3dc3274752/packages/sakuli-core/src/runner/js-script-executor.class.ts#L31-L33

But the rejected promise is never been handled hence Sakuli dying silently
https://github.com/sakuli/sakuli/blob/7e7b2aaebbd1ceb947a3b1ca54b59a3dc3274752/packages/sakuli-core/src/runner/js-script-executor.class.ts#L36-L38


Adding `.catch(rej)` solves the issue.
