### ISSUE TITLE
Cryptic error message in case that an image could not be found due to the similarity

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#325]
As a Sakuli user, I'd like to obtain a more precise error message in case a picture could not be matched because of an insufficient similarity, to be able to debug my check more efficiently.

**Additional information**
In case such an issue occurs, the Sakuli output states:
```
Error in testcase foo: Error in action: find 
undefined
Error: Error in action: find 
undefined
    at Object.<anonymous> (/headless/.nvm/versions/node/v10.18.1/lib/node_modules/@sakuli/cli/node_modules/@sakuli/legacy/dist/context/common/actions/action.function.js:83:31)
    at step (/headless/.nvm/versions/node/v10.18.1/lib/node_modules/@sakuli/cli/node_modules/@sakuli/legacy/dist/context/common/actions/action.function.js:32:23)
    at Object.throw (/headless/.nvm/versions/node/v10.18.1/lib/node_modules/@sakuli/cli/node_modules/@sakuli/legacy/dist/context/common/actions/action.function.js:13:53)
    at rejected (/headless/.nvm/versions/node/v10.18.1/lib/node_modules/@sakuli/cli/node_modules/@sakuli/legacy/dist/context/common/actions/action.function.js:5:65)[Thu Jan 30 2020 09:23:52 GMT+0000 (Coordinated Universal Time)] INFO: Saved error screenshot at 'sakuli_test_suite/_logs/_screenshots/sakuli_test_suite_foobar/2020-01-30T09-23-52_error_sakuli_test_suite_foo.png'
```

If you have a look in the logs, you'll find that:
`Failed to locate bar.png. Reason: No match for bar.png. Required: 0.99, given: 0.8469456732273102`

**Comment by s1hofmann** [comment]
See https://github.com/sakuli/sakuli-enterprise-forwarder/issues/49
