### ISSUE TITLE
Cryptic error message in case the image is too large - Automatic image downscale?

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#326]
As a Sakuli user, I want Sakuli to downscale images automatically if they are too large to be applied on the screen, so that my check does not fail with a cryptic error message. If an automated downscale is not possible, I want a more precise error message to be able to debug my checks more efficiently.

**Additional information**
In such a case, the Sakuli output states:
```
Error in testcase foo: Error in action: find 
undefined
Error: Error in action: find 
undefined
    at Object.<anonymous> (/headless/.nvm/versions/node/v10.18.1/lib/node_modules/@sakuli/cli/node_modules/@sakuli/legacy/dist/context/common/actions/action.function.js:83:31)
    at step (/headless/.nvm/versions/node/v10.18.1/lib/node_modules/@sakuli/cli/node_modules/@sakuli/legacy/dist/context/common/actions/action.function.js:32:23)
    at Object.throw (/headless/.nvm/versions/node/v10.18.1/lib/node_modules/@sakuli/cli/node_modules/@sakuli/legacy/dist/context/common/actions/action.function.js:13:53)
    at rejected (/headless/.nvm/versions/node/v10.18.1/lib/node_modules/@sakuli/cli/node_modules/@sakuli/legacy/dist/context/common/actions/action.function.js:5:65)[Thu Jan 30 2020 09:28:45 GMT+0000 (Coordinated Universal Time)] INFO: Saved error screenshot at 'sakuli_test_suite/_logs/_screenshots/sakuli_test_suite_foo2020-01-30T09-28-45_error_sakuli_test_suite_foo.png'
```

If you look into the logs, you'll find:
`ERROR: Failed to locate bar.png. Reason: Searching for bar.png failed. Reason: 'OpenCV Error: (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) in matchTemplate, in file /home/travis/build/nut-tree/npm-opencv-build/opencv/opencv/modules/imgproc/src/templmatch.cpp, line 1112, status -215'`

**Comment by svettwer** [comment]
@s1hofmann you added the "To Discuss" label but no further information. What is it you want to talk about :smile:

**Comment by svettwer** [comment]
@s1hofmann mentioned, that this issue should not occur anymore. Please verify that this is still valid.

**Comment by cliffle** [comment]
With `2.3.1-next.278`, you get the following error message:
```
Error: Error in action: find 
Searching for test.png failed. Reason: 'No match with required confidence 0.99. Best match: 0 at (0, 0, 810, 500)'
at /headless/.nvm/versions/node/v12.18.3/lib/node_modules/@sakuli/cli/node_modules/@sakuli/legacy/dist/context/common/actions/action.function.js:14:19
```

**Comment by svettwer** [comment]
consider upstream contribution to https://github.com/nut-tree/nut.js

**Comment by svettwer** [comment]
PR for https://github.com/nut-tree/nut.js/issues/169 is open :tada:

**Comment by svettwer** [comment]
nut-tree/nut.js#169 was accepted. Waiting for release to update sakuli
