### ISSUE TITLE
Missing newlines in logfile

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#385]
As a sakuli user, I want timestamps to be positioned at the beginning of the line, so that I'm able to identify the time an error occurred efficiently.

**Additional information**
It seems that error messages printed to the log files are missing a new line at the end. Here is a log snippet showing the issue.
```
[Mon Mar 09 2020 17:53:21 GMT+0100 (GMT+01:00)] ERROR: Error in testcase FooBar: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=79.0.3945.79)
NoSuchWindowError: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=79.0.3945.79)
    at Object.throwDecodedError (/headless/.nvm/versions/node/v10.18.1/lib/node_modules/@sakuli/cli/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/headless/.nvm/versions/node/v10.18.1/lib/node_modules/@sakuli/cli/node_modules/selenium-webdriver/lib/http.js:560:13)
    at Executor.execute (/headless/.nvm/versions/node/v10.18.1/lib/node_modules/@sakuli/cli/node_modules/selenium-webdriver/lib/http.js:486:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)[Mon Mar 09 2020 18:01:53 GMT+0100 (GMT+01:00)] ERROR: Error in testcase FooBar: chrome not reachable
```
As you can see, the stacktrace ends with the timestamp of the next error.
`at process._tickCallback (internal/process/next_tick.js:68:7)[Mon Mar 09 2020 18:01:53 GMT+0100 (GMT+01:00)] ERROR: Error in testcase FooBar: chrome not reachable`

**Acceptance criteria**
- [x] Timestamp after errors are placed at the beginning of a new line

**Comment by svettwer** [comment]
Refinement required

**Comment by cliffle** [comment]
This behavior is caused by `defaultStringifier` in `default-stringifier.function.ts`.
When something is logged with additional `data` (in this example the stack trace), the returned string does not end with an `EOL`.
