### ISSUE TITLE
Action Errors preserves even if they are caught by programm flow

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#597]
**Version**

2.4.1-next.405

**Short overview**

When you try and catch an error in the program flow of the sakuli check, the error is correctly caught so that the program flow resumes to the catch block, but the test will fail anyway with this error since it seems that sakuli "remembers" the error.

This behavior seems to happen everytime an action causes a error. 

**Detailed error description**

**Steps to reproduce error**

```typescript
(async () => {
    const tc = new TestCase("Issue");
    const env = new Environment();
    try {
        await _navigateTo('https://google.com/')

        try {
          await _click(_div('something-that-not-exists'))
        } catch(e) {
          Logger.logInfo('Well everything should be fine')
        }

    } catch (e) {
        await tc.handleException(e);
    } finally {
        await tc.saveResult();
    }
})()

```

In the example above the log Info `"Well everything should be fine"` is logged so, as a Testauthor I would assume that the test will run successfully.

Test log is as follows:

```
 ____            _              _   _ 
 / ___|    __ _  | | __  _   _  | | (_)
 \___ \   / _` | | |/ / | | | | | | | |
  ___) | | (_| | |   <  | |_| | | | | |
 |____/   \__,_| |_|\_\  \__,_| |_| |_|
                                       
========================================

Initialized Sakuli with 1 Testcases

Writing logs to: itsm/_logs/sakuli.log
[Tue Feb 02 2021 10:42:10 GMT+0000 (Coordinated Universal Time)] INFO: Loaded Sakuli with checkMkForwarderPreset,gearmanForwarderPreset,icinga2ForwarderPreset,prometheusPreset,legacyPreset,ocrPreset
[Tue Feb 02 2021 10:42:10 GMT+0000 (Coordinated Universal Time)] DEBUG: Checkmk Configuration:
enabled: false
spoolDir: /var/lib/check_mk_agent/spool
spoolfilePrefix: sakuli_suite
freshness: 600
piggybackHostName: 
sectionName: local
serviceDescription: 
outputDetails: true
url:
[Tue Feb 02 2021 10:42:10 GMT+0000 (Coordinated Universal Time)] DEBUG: Gearman Configuration:
enabled: false,
serverHost: 10.250.252.20,
serverPort: 4730,
serviceType: passive,
serverQueue: check_results,
encryption: true,
secretKey: ***,
nagiosHost: sakuli_client,
nagiosCheckCommand: check_sakuli,
nagiosServiceDescription: ,
nagiosTemplateSuiteSummaryMaxLength: 200,
nagiosTemplateScreenshotDivWidth: 640,
outputDetails: true
[Tue Feb 02 2021 10:42:10 GMT+0000 (Coordinated Universal Time)] DEBUG: Icinga2 Configuration:
enabled: false,
allowInsecure: false,
apiHost: undefined,
apiPort: 5665,
apiUserName: ,
apiPassword: ,
checkCommand: check_sakuli,
checkSource: check_sakuli,
hostName: ,
serviceDescription:
[Tue Feb 02 2021 10:42:10 GMT+0000 (Coordinated Universal Time)] DEBUG: Prometheus Forwarder Configuration:
enabled: false,
apiHost: ,
apiPort: 9091,
apiJob:
[Tue Feb 02 2021 10:42:10 GMT+0000 (Coordinated Universal Time)] INFO: Started Execution
[Tue Feb 02 2021 10:42:11 GMT+0000 (Coordinated Universal Time)] DEBUG: Created webdriver
[Tue Feb 02 2021 10:42:11 GMT+0000 (Coordinated Universal Time)] INFO: Started Testsuite itsm
[Tue Feb 02 2021 10:42:11 GMT+0000 (Coordinated Universal Time)] INFO: Started Testcase Issue
[Tue Feb 02 2021 10:42:11 GMT+0000 (Coordinated Universal Time)] DEBUG: New similarity value: 0.99
[Tue Feb 02 2021 10:42:12 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:13 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:13 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:13 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:13 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:13 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:13 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:13 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:14 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:14 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:14 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:14 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:14 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:14 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:14 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:14 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:15 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:15 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:15 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:15 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:15 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:15 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:15 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:15 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 120 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:15 GMT+0000 (Coordinated Universal Time)] DEBUG: Number of detected frames: 1
[Tue Feb 02 2021 10:42:15 GMT+0000 (Coordinated Universal Time)] DEBUG: Querying frame Nr.: 0
[Tue Feb 02 2021 10:42:16 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:16 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:16 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:16 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:16 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:16 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:16 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:16 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:17 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:17 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:17 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:17 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:17 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:17 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:17 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:17 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:18 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:18 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:18 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:18 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:18 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:18 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:18 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:18 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] DEBUG: Converted string "something-that-not-exists" to regex /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] DEBUG: Found 32 Elements for RegEx: /^\s*something-that-not-exists\s*$/
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] DEBUG: Received TimoutError when searching for element in frame Nr.: 0, not updating error history
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] INFO: Well everything should be fine
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] INFO: Finished Step UNNAMED with state Error 7.897s
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] DEBUG: Gearman forwarding disabled via properties.
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] INFO: Finished Testcase Issue with state Error 7.901s
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] DEBUG: Gearman forwarding disabled via properties.
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] INFO: Finished Testsuite itsm with state Error 8.001s
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] DEBUG: Gearman forwarding disabled via properties.
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] DEBUG: Closed webdriver
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] INFO: Finished Execution
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] DEBUG: CheckMK forwarding disabled via properties.
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] DEBUG: Gearman forwarding disabled via properties.
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] DEBUG: Icinga2 forwarding disabled via properties.
[Tue Feb 02 2021 10:42:19 GMT+0000 (Coordinated Universal Time)] DEBUG: Prometheus forwarding disabled via properties.

Failed to perform action click:

TimeoutError: Cannot find Element within 3000ms by query:
locator: By(css selector, div)
identifier: something-that-not-exists
Wait timed out after 3066ms
at /headless/.nvm/versions/node/v14.15.4/lib/node_modules/@sakuli/cli/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! Test failed.  See above for more details.
~
```

**Comment by svettwer** [comment]
Acceptance criteria:
- [ ] Ensure that the test execution context only receives errors in `handleException`.
