### ISSUE TITLE
Sakuli Windows installation

### ISSUE THREAD

**Issue by Dominik-Robert** [sakuli/sakuli#625]
**Version** 
The version of npm: 7.6.3
The version of node:  v14.16.1
windows
Edition : Windows 10 Pro
Version: 20H2
Build: 19042.906
Performance: Windows Feature Experience Pack 120.2212.551.0

**Short overview**
I can´t install sakuli on a windows system. The installation of @sakuli/cli will always fail

**Detailed error description**
The error that I get is the foillowing:
```bash
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path D:\Programmieren\Sakuli\node_modules\opencv4nodejs-prebuilt
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
npm ERR! Installing prebuilt OpenCV vundefined for plattform win32
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-win32@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\Dominik\AppData\Local\npm-cache\_logs\2021-04-19T11_21_34_298Z-debug.log
npm ERR! child_process.js:655
npm ERR!     throw err;
npm ERR!     ^
npm ERR!
npm ERR! Error: Command failed: npm install @nut-tree/opencv-build-win32@undefined
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-win32@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\Dominik\AppData\Local\npm-cache\_logs\2021-04-19T11_21_34_298Z-debug.log
npm ERR!
npm ERR!     at checkExecSyncError (child_process.js:616:11)
npm ERR!     at execSync (child_process.js:652:15)
npm ERR!     at install (D:\Programmieren\Sakuli\node_modules\opencv4nodejs-prebuilt\install\dependencies.js:5:5)
npm ERR!     at Object.<anonymous> (D:\Programmieren\Sakuli\node_modules\opencv4nodejs-prebuilt\install\dependencies.js:26:5)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
npm ERR!     at internal/main/run_main_module.js:17:47 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(394) [Uint8Array] [
npm ERR!       110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!       101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!       109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!       103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!       105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!       102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!       117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!        99, 118,  45,  98, 117, 105, 108, 100,  45, 119, 105, 110,
npm ERR!        51,  50,  64, 117,
npm ERR!       ... 294 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 18176,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(394) [Uint8Array] [
npm ERR!     110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!     101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!     109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!     103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!     105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!     102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!     117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!      99, 118,  45,  98, 117, 105, 108, 100,  45, 119, 105, 110,
npm ERR!      51,  50,  64, 117,
npm ERR!     ... 294 more items
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dominik\AppData\Local\npm-cache\_logs\2021-04-19T11_21_57_348Z-debug.log
```

**Steps to reproduce error**
Use the following package.json and run a npm install to install all the including packages. 
```json
{
  "name": "Sakuli",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chromedriver": "90.0.0",
    "@sakuli/cli": "2.3.0"
  }
}
```
The installation will also fail with the version "2.4.0" and "2.5.0" ...

**Comment by svettwer** [comment]
Hi! :wave: 

Thx for reaching out. Please always use the latest version of Sakuli, which is 2.5.0, currently. This version also includes support for node 14.
Did you have a look at the getting [started guide ](https://sakuli.io/docs/getting-started/) in our documentation? There are several steps to perform before Sakuli is able to run on windows hosts.

**Comment by svettwer** [comment]
After some research, it seems that the issue relates to npm 7.

**Comment by svettwer** [comment]
Seems to relate to https://github.com/nut-tree/opencv4nodejs/issues/9.

Please try to use Sakuli with npm 6.

**Comment by Dominik-Robert** [comment]
It worked with npm6. Thank you!

**Comment by Dominik-Robert** [comment]
It worked with npm6. Thank you!
