### ISSUE TITLE
execution with safari fails

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli#70]
**Version**
Mac OSX 10.14.4 (18E226)
Safari Version 12.1 (14607.1.40.1.4)
**Short overview**
Sakuli tests fail when executing with Safari Browser
Test-Results are falsely green.
**Detailed error description**
```
Last login: Mon May 20 11:44:06 on ttys005
eucken:myFirstTests nze$ npx sakuli run my-sut --browser=safari
  ____            _              _   _ 
 / ___|    __ _  | | __  _   _  | | (_)
 \___ \   / _` | | |/ / | | | | | | | |
  ___) | | (_| | |   <  | |_| | | | | |
 |____/   \__,_| |_|\_\  \__,_| |_| |_|
                                       
========================================

(node:5287) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
Webdriver doesn't quit reliably { SessionNotCreatedError: Request body does not contain required parameter 'capabilities'.
    at Object.throwDecodedError (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/http.js:441:30)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/safari.js:253:41)
    at createDriver (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/index.js:660:16)
    at LegacyLifecycleHooks.<anonymous> (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:87:22)
    at step (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:43:23)
    at Object.next (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:24:53)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:14:12)
From: Task: WebDriver.manage().window().maximize()
    at thenableWebDriverProxy.schedule (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Window.maximize (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/webdriver.js:1686:25)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:237:74
    at step (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:36:23)
    at Object.next (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:17:53)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:7:12)
    at _navigateTo (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:227:16)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:92:55
From: Task: WebDriver.quit()
    at thenableWebDriverProxy.schedule (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at thenableWebDriverProxy.quit (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/webdriver.js:840:23)
    at LegacyLifecycleHooks.<anonymous> (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:113:61)
    at step (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:43:23)
    at Object.next (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:24:53)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:14:12)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:107:77
    at Object.ifPresent (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/commons/dist/maybe.js:23:13) name: 'SessionNotCreatedError', remoteStacktrace: '' }
✓ suite my-sut .................................. 0.46s
   ✓ case testcase ................................ 0.40s
    ✓ step UNNAMED ................................ 0.40s

[2019-05-20T11:44:30.514+02:00] Start action navigateTo
[2019-05-20T11:44:30.923+02:00] Finished Execution


/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^

SessionNotCreatedError: Request body does not contain required parameter 'capabilities'.
    at Object.throwDecodedError (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/http.js:441:30)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/safari.js:253:41)
    at createDriver (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/index.js:660:16)
    at LegacyLifecycleHooks.<anonymous> (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:87:22)
    at step (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:43:23)
    at Object.next (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:24:53)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:14:12)
From: Task: WebDriver.manage().window().maximize()
    at thenableWebDriverProxy.schedule (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Window.maximize (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/webdriver.js:1686:25)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:237:74
    at step (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:36:23)
    at Object.next (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:17:53)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:7:12)
    at _navigateTo (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:227:16)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/sahi/action/action-api.function.js:92:55
From: Task: WebDriver.quit()
    at thenableWebDriverProxy.schedule (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at thenableWebDriverProxy.quit (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/selenium-webdriver/lib/webdriver.js:840:23)
    at LegacyLifecycleHooks.<anonymous> (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:113:61)
    at step (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:43:23)
    at Object.next (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:24:53)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:14:12)
    at /Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/legacy/dist/context/legacy-Lifecycle-hooks.class.js:107:77
    at Object.ifPresent (/Users/nze/Git/sakuli2snippets/myFirstTests/node_modules/@sakuli/commons/dist/maybe.js:23:13)
eucken:myFirstTests nze$ 
```

Reproduce:
```
(async () => { 
    const testCase = new TestCase();
    try {
        await _navigateTo("https://sakuli.io");              // 1
        testCase.endOfStep("Open Landing Page",5);           // 2
        await _click(_link("Getting started"));              // 3
        testCase.endOfStep("Navigate to Getting Started",3); // 4
        await _highlight(_code("npm init"));                 // 5
        testCase.endOfStep("Find npm init code sample");     // 6
    } catch (e) {
        testCase.handleException(e);
    } finally {
        testCase.saveResult();
    }

})().then(done);
```

**Comment by s1hofmann** [comment]
You have to make sure that remote automation is enabled in Safari: https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari
